version: '2'

services:
  db:
    image: 'mysql:5.7'
    environment:
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'ewvbcxvesd324rfg4532hjnh'
    ports:
      - '3007:3306'
    volumes:
      - '/Users/shared/mysql:/var/lib/mysql'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    volumes:
      - 'redis:/var/lib/redis/data'

  website:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    ports:
      - '7007:7007'
    volumes:
      - '.:/fyoga'
    env_file:
      - '.fyoga.env'

#  sidekiq:
#    depends_on:
#      - 'db'
#      - 'redis'
#    build: .
#    command: sidekiq -C config/sidekiq.yml
#    volumes:
#      - '.:/eqms'
#    env_file:
#      - '.eqms.env'



volumes:
  redis:
  mysql: