version: '3'

services:
  db:
    image: 'mysql:5.7'
    environment:
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'ewvbcx3jci59sp4532hjnh'
    ports:
      - '3007:3306'
    volumes:
      - '/data/mysql:/var/lib/mysql'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    volumes:
      - 'redis:/var/lib/redis/data'

  website:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - './public:/fyoga/public'
    env_file:
      - '.env'

#  sidekiq:
#    depends_on:
#      - 'db'
#      - 'redis'
#    build: .
#    command: sidekiq -C config/sidekiq.yml
#    volumes:
#      - '.:/eqms'
#    env_file:
#      - '.eqms.env'



volumes:
  redis:
  mysql: